#define IDR_DESKTOP        1
#define IDR_WHITE          2
#define IDR_BLUE           3
#define IDR_RED            4
#define IDR_PINK           5
#define IDR_GREEN          6
#define IDR_CYAN           7
#define IDR_YELLOW         8

#define IDM_DOCUMENTS    512
#define IDM_WHITE        513
#define IDM_BLUE         514
#define IDM_RED          515
#define IDM_PINK         516
#define IDM_GREEN        517
#define IDM_CYAN         518
#define IDM_YELLOW       519
#define IDM_EXIT         520
#define IDM_CONTINUE     521
#define IDM_FOO          522
#define IDM_BAR          523
#define IDM_FOOBAR       524
#define IDM_DOTHIS       525
#define IDM_DOTHAT       526
#define IDM_DOTHEOTHER   527
#define IDM_OPTIONS      528
